### ISSUE TITLE
can't find a csv file in output folder.

### ISSUE THREAD

**Issue by HJun16** [Airwhf/MEIAT-CMAQ#10]
I have tried run your script, but get a error:
[Errno 2] No such file or directory: './output/source/source-MEIC-transportation-2017-07.csv'

This might occur Line 612-613 of src.py. I can't find this civ file.

```
    source_file = f"./output/source/source-{label}-{sector}-{inventory_year}-{mm}.csv"
    data = pd.read_csv(source_file)
```

**Comment by Airwhf** [comment]
Hi, 

Thanks for the writing. Can you show the `namelist.input` file.

If you do not set the `create_source ` as 1, there is no source file output.

So you can try to reset the `namelist.input` as follows, and remove the output directory and try again.

```
&control
    create_grid = 1,
    grid_info = 1,
    create_factor = 1,
    coarse_emission = 1,
    create_source = 1,
 /
```

Cheers,
Haofan
