### ISSUE TITLE
CMAQ5.3  ERROR: Surrogate Species PAL on emission stream   1 has units G/S\00\00\00\00\00\00\00\00\00\00\00\00\00 which are unkown to CMAQ

### ISSUE THREAD

**Issue by MINISUPE** [Airwhf/MEIAT-CMAQ#12]
``hi，MEIAT-CMAQ administrator:
I have been using this tool for two weeks now, but it took me over a week to find the cause of the error. I am very distressed because I have been encountering the same error all along:

     |> Checking Emissions Surrogate Units:
     ======================================

     *** ERROR ABORT in subroutine CHECK_EMIS_UNITS on PE 000
     ERROR: Surrogate Species PAL on emission stream   1 has units G/S\00\00\00\00\00\00\00\00\00\00\00\00\00 which are unkown to 
     CMAQ. Please correct them to proceed.
     PM3EXIT:  date&time specified as 0
     Date&time specified as 0

I strictly followed the case study:   [使用2017年的MEIC清单制作珠三角的排放文件](https://github.com/Airwhf/MEIAT-CMAQ/blob/53b2df42a2b66ce5382ac482e9449b5d6f16fa09/Doc/1-adopt_meic_for_prd_emission_file.md)
MEIC download:
```
    输出时间分辨率设置逐月
    输出排放部门设置5部门
    输出空间分辨率设置兰伯特投影
    第一标准纬度：25度, 投影中心纬度：34度,
    第二标准纬度：40度, 投影中心经度：110度,
    左下角横坐标：-3096000米,
    左下角纵坐标：-2286000米,
    X方向分辨率：36千米, Y方向分辨率：36千米,
    X方向网格数：172个, Y方向网格数：127个
    物种SO2,NOx,CO,NMVOC,NH3,PM10,PM2.5,BC,OC
    输出VOC化学机制设置CB05
```
namelist.input
```
&global
    griddesc_file = "input/GRIDDESC.22"
    griddesc_name = "20181201_cd"
    big_grid_file = "shapefile/MEIC-0P25.shp"
    geotiff_dir = "Z:/AAATOGETER/tif"
    inventory_label = "MEIC"
    inventory_year = "2018"
    sectors = 'transportation', 'residential', 'power', 'agriculture', 'industry'
    allocator = 'line', 'landscan-global-2017_nodata.tif', 'power.tif', 'agriculture.tif', 'industry.tif',
    allocator_type = "line", "raster", "raster", "raster", "raster"
    inventory_mechanism = "MEIC-CB05"
    target_mechanism = "CB06"
    start_date = "2018-12-01"
    end_date = "2018-12-01"
    cores = 4
 /

 &line
    line_files = "motorway.shp", "primary.shp", "residential.shp", "secondary.shp"
    line_factors = 0.435798, 0.326848, 0.081712, 0.155642,
 /

 &control
    create_grid = 1,
    grid_info = 1,
    create_factor = 1,
    coarse_emission = 1,
    create_source = 1,
 /
```

python .\coarse_emission_2_fine_emission.py
python .\Create-CMAQ-Emission-File.py
As of this step, there have been no errors reported. Then I also completed the data preparation for ICON, BCON, MCIP, and MASK

Finally, send an error message:

> 
>  |> Check Emissions Mapping:
>      +============================
>      =============================================================================
>      |> SCALING EMISSIONS CONSISTENT WITH EMISSIONS CONTROL FILE SUPPLIED BY USER
>      =============================================================================
>      |> Regions Available for Scaling:
>      =================================
>         Number  Region Label        File Label          Variable
>         ------  ------------        ----------          --------
>           1     EVERYWHERE          N/A                 N/A
>      |> Map Available Emissions Surrogates to Defaults:
>      ==================================================
> 
>      |> Checking Emissions Surrogate Units:
>      ======================================
>      *** ERROR ABORT in subroutine CHECK_EMIS_UNITS on PE 000
>      ERROR: Surrogate Species ALD2 on emission stream   1 has units MOLES/S\00\00\00\00\00\00\00\00\00 which are unkown to CMAQ. Please correct them to proceed.
>  PM3EXIT:  date&time specified as 0
>      Date&time specified as 0
> 
Attached are run_cctm.csh and CTM_LOG
[run_cctm_meic_20220320.zip](https://github.com/user-attachments/files/16122235/run_cctm_meic_20220320.zip)

**Comment by Airwhf** [comment]
检查一下你的排放文件中的 units 部分为什么会出现以下的乱码：

```
G/S\00\00\00\00\00\00\00\00\00\00\00\00\00
```

有可能是你在运行或者写入物种文件的过程中出现了中文或者其他特殊字符。
